version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - nso-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  nso-data: